<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- ¡AQUÍ ESTÁ LA MAGIA! Cambiamos la arquitectura a 32 bits -->
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>
  </PropertyGroup>
</Project>